#!/system/bin/sh
#==============================================================
#       FILE		: LS00kernelconfig
#       AUTHOR		: ImbaWind @ XDA
#       DESCRIPTION	: Shell Script Advanced Features
#                     Execute on boot to set kernel param
#       GitHub		: https://github.com/ycsin
#==============================================================
SCRIPT_VERSION=1
. "/system/bin/SSAF_INCL"

MOUNT_RW

lock_value 1898000 /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
lock_value 455000 /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
lock_value interactive /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

lock_value 2652000 /sys/devices/system/cpu/cpu4/cpufreq/scaling_max_freq
lock_value 741000 /sys/devices/system/cpu/cpu4/cpufreq/scaling_min_freq
lock_value interactive /sys/devices/system/cpu/cpu4/cpufreq/scaling_governor

lock_value 572000 /sys/kernel/gpu/gpu_max_clock
lock_value 260000 /sys/kernel/gpu/gpu_min_clock
lock_value Interactive /sys/kernel/gpu/gpu_governor

MOUNT_RO