#!/system/bin/sh
#==============================================================
#       FILE		: LS00kernelconfig
#       AUTHOR		: ImbaWind @ XDA
#       DESCRIPTION	: Shell Script Advanced Features
#                     Execute on boot to set kernel param
#       GitHub		: https://github.com/ycsin
#==============================================================
SCRIPT_VERSION=1

. "/system/bin/SSAF_INCL"
MOUNT_RW
for i in 0 1 2 3; do

	chmod 0666 /sys/devices/system/cpu/cpu$i/cpufreq/scaling_max_freq
	echo 1690000 > /sys/devices/system/cpu/cpu$i/cpufreq/scaling_max_freq
	chmod 0444 /sys/devices/system/cpu/cpu$i/cpufreq/scaling_max_freq

done

for i in 0 1 2 3; do

	chmod 0666 /sys/devices/system/cpu/cpu$i/cpufreq/scaling_min_freq
	echo 1690000 > /sys/devices/system/cpu/cpu$i/cpufreq/scaling_min_freq
	chmod 0444 /sys/devices/system/cpu/cpu$i/cpufreq/scaling_min_freq

done

for i in 4 5 6 7; do

	chmod 0666 /sys/devices/system/cpu/cpu$i/cpufreq/scaling_max_freq
	echo 2496000 > /sys/devices/system/cpu/cpu$i/cpufreq/scaling_max_freq
	chmod 0444 /sys/devices/system/cpu/cpu$i/cpufreq/scaling_max_freq

done

for i in 4 5 6 7; do

	chmod 0666 /sys/devices/system/cpu/cpu$i/cpufreq/scaling_min_freq
	echo 2496000 > /sys/devices/system/cpu/cpu$i/cpufreq/scaling_min_freq
	chmod 0444 /sys/devices/system/cpu/cpu$i/cpufreq/scaling_min_freq

done

for i in 0 1 2 3; do

	chmod 0666 /sys/devices/system/cpu/cpu$i/cpufreq/scaling_governor
	echo interactive > /sys/devices/system/cpu/cpu\$i/cpufreq/scaling_governor
	chmod 0444 /sys/devices/system/cpu/cpu$i/cpufreq/scaling_governor

done

for i in 4 5 6 7; do

	chmod 0666 /sys/devices/system/cpu/cpu$i/cpufreq/scaling_governor
	echo interactive > /sys/devices/system/cpu/cpu\$i/cpufreq/scaling_governor
	chmod 0444 /sys/devices/system/cpu/cpu$i/cpufreq/scaling_governor

done
MOUNT_RO