#!/system/bin/sh
#==============================================================
#       FILE		: LS00resetdns
#       AUTHOR		: ImbaWind @ XDA
#       DESCRIPTION	: Shell Script Advanced Features
#                     Execute on boot to set dns
#       GitHub		: https://github.com/ycsin
#==============================================================
SCRIPT_VERSION=1

iptables -t nat -A OUTPUT -p tcp --dport 53 -j DNAT --to-destination 1.1.1.1:53
iptables -t nat -A OUTPUT -p udp --dport 53 -j DNAT --to-destination 1.0.0.1:53
iptables -t nat -D OUTPUT -p tcp --dport 53 -j DNAT --to-destination 1.1.1.1:53 || true
iptables -t nat -D OUTPUT -p udp --dport 53 -j DNAT --to-destination 1.0.0.1:53 || true
iptables -t nat -I OUTPUT -p tcp --dport 53 -j DNAT --to-destination 1.1.1.1:53
iptables -t nat -I OUTPUT -p udp --dport 53 -j DNAT --to-destination 1.0.0.1:53