#!/system/bin/sh
#==============================================================
#       FILE		: LS00powercfg
#       AUTHOR		: ImbaWind @ XDA
#       DESCRIPTION	: Shell Script Advanced Features
#                     Execute on boot to powercfg setting
#       GitHub		: https://github.com/ycsin
#==============================================================
SCRIPT_VERSION=1

powercfg balance